### ISSUE TITLE
用python 获取豆瓣简介失败

### ISSUE THREAD

**Issue by jzz3933** [Rhilip/pt-gen-cfworker#12]
# 复现步骤

1. 请指出是哪个域名能够复现该问题？

- [ ] https://ptgen.rhilip.info/
- [ ] https://ptgen.rhilip.workers.dev/

2. 错误描述：
利用python requests模块抓取某个豆瓣链接对应的简介时，返回数据一直报错，报错信息见其他信息，程序中已经添加浏览器中看到的所有Header,包括 headers, authority, x-requested-with等，但仍然返回失败。
不太理解，提示的“Miss key of `site` or `sid`”是什么意思，是不是与cloudflare有关系，还望答疑解惑，非常感谢！

3. 错误链接？

https://movie.douban.com/subject/24733428/

# 其他信息
{
  "success": false,
  "error": "Miss key of `site` or `sid` , or input unsupported resource `url`.",
  "format": "",
  "copyright": "Powered by @Rhilip",
  "version": "0.6.1",
  "generate_at": 1609575424075
}

**Comment by Rhilip** [comment]
不能复现，请重新阅读requests文档，或直接点击下面链接进行测试
https://ptgen.rhilip.info/?url=https://movie.douban.com/subject/24733428

**Comment by Rhilip** [comment]
另请贴一下你python请求代码

**Comment by jzz3933** [comment]
感谢回复，在分析链接（https://ptgen.rhilip.info/?url=https://movie.douban.com/subject/24733428）后，已经解决问题。
问题是：在给https://ptgen.rhilip.info提交douban网址的时候，虽然浏览器是将douban网址的所有字符进行了URL编码，包括“:  //”等，但如果python也URL编码后提交，则会返回数据失败，此时只需提交原URL链接即可。

另外，确实有一定概率会出现internal error 这个错误，总的来说，感谢提供了一个很好的工具！

> 不能复现，请重新阅读requests文档，或直接点击下面链接进行测试
> https://ptgen.rhilip.info/?url=https://movie.douban.com/subject/24733428

**Comment by Rhilip** [comment]
建议多看requests的文档，

```python
import requests

endpoint = 'http://ptgen.rhilip.info'

# 下面两种都是可以的
r = requests.get(endpoint, params={'url':'https://movie.douban.com/subject/24733428'})
r = requests.get(endpoint, params={'site':'douban','sid':'24733428'})

print(r.json())

```
