### ISSUE TITLE
无法获取豆瓣下的影视信息

### ISSUE THREAD

**Issue by deskmonster** [Rhilip/pt-gen-cfworker#13]
# 复现步骤
直接请求https://ptgen.rhilip.info/?url=https://movie.douban.com/subject/24733428
或者进入ptgen输入豆瓣链接后请求都得到报错

1. 请指出是哪个域名能够复现该问题？

- [ ] https://ptgen.rhilip.info/
- [ ] https://ptgen.rhilip.workers.dev/
-

2. 如果是非官方域名出现的问题，在上面的官方API Point中能否复现？（使用官方域名请跳过）

- [ ] 在 https://ptgen.rhilip.info/ 域名中能复现。
- [ ] 在 https://ptgen.rhilip.workers.dev/ 域名中能复现。
- [ ] 均不能复现。

3. 错误链接？

https://ptgen.rhilip.info/?url=https://movie.douban.com/subject/24733428

# 其他信息

{
  "success": false,
  "error": "Internal Error, Please contact @Rhilip. Exception: Cannot read property 'replace' of null",
  "format": "",
  "copyright": "Powered by @Rhilip",
  "version": "0.6.1",
  "generate_at": 1609582015995
}

**Comment by Rhilip** [comment]
![image](https://user-images.githubusercontent.com/13842140/103455200-0ac96980-4d26-11eb-965f-df3af0874895.png)
不能复现

**Comment by deskmonster** [comment]
似乎是我代理的问题，我关闭代理以后就能正常解析了。
