### ISSUE TITLE
Indienova 无法抓取信息

### ISSUE THREAD

**Issue by deskmonster** [Rhilip/pt-gen-cfworker#15]
# 复现步骤

1. 请指出是哪个域名能够复现该问题？

- [x] https://ptgen.rhilip.info/
- [x] https://ptgen.rhilip.workers.dev/

3. 错误链接？

https://indienova.com/game/endzone-a-world-apart

# 其他信息

IndieaNova现在限制了登录用户访问GameDB。受此影响，脚本无法抓取相关信息。

**Comment by Rhilip** [comment]
如你为自建用户，请考虑添加环境变量 `INDIENOVA_COOKIE`，其值示例如下：

![image](https://user-images.githubusercontent.com/13842140/113134186-165bfc00-9253-11eb-9261-ea31be3a1006.png)

**Comment by moerfutin** [comment]
请教DOUBAN_COOKIE的格式如何设置呀？
