### ISSUE TITLE
English ? 

### ISSUE THREAD

**Issue by DrunkenMonkey1** [Rhilip/pt-gen-cfworker#19]
# 复现步骤

1. 请指出是哪个域名能够复现该问题？

- [ ] https://ptgen.rhilip.info/
- [ ] https://ptgen.rhilip.workers.dev/
- [ ] 其他非官方API Point： （请修改成对应域名）

2. 如果是非官方域名出现的问题，在上面的官方API Point中能否复现？（使用官方域名请跳过）

- [ ] 在 https://ptgen.rhilip.info/ 域名中能复现。
- [ ] 在 https://ptgen.rhilip.workers.dev/ 域名中能复现。
- [ ] 均不能复现。

3. 错误链接？

# 其他信息

**Comment by Rhilip** [comment]
Could you explain more?
This repo is not prepared for i18n well. 
Because most of information resource is Chinese Only.
For example, Douban and Bangumi.

At now, you can re-generate the information text from the field in api response.

**Comment by qq289531426** [comment]
已经按照教程使用 Cloudflare Worker 构建 Pt-Gen

**Comment by qq289531426** [comment]
按照教程部署基于Cloudflare Worker的Pt-Gen
1.无Node环境直接部署
复制了script.js 内的参数到Worker面板，保存之后会提示错误代码10013这个怎么解决呢
