### ISSUE TITLE
希望增加豆瓣cookie获取

### ISSUE THREAD

**Issue by haig233** [Rhilip/pt-gen-cfworker#20]
# 复现步骤

1. 请指出是哪个域名能够复现该问题？

- [X] https://ptgen.rhilip.info/
- [X] https://ptgen.rhilip.workers.dev/
- [] 其他非官方API Point： （请修改成对应域名）

2. 如果是非官方域名出现的问题，在上面的官方API Point中能否复现？（使用官方域名请跳过）

- [X] 在 https://ptgen.rhilip.info/ 域名中能复现。
- [x] 在 https://ptgen.rhilip.workers.dev/ 域名中能复现。
- [ ] 均不能复现。

3. 错误链接？
https://ptgen.rhilip.info/?url=https://movie.douban.com/subject/4848114/

# 其他信息

是否能增加豆瓣cookie，来获取一些只能登录才能看到的页面的信息
例如缘之空，https://movie.douban.com/subject/4848114/

**Comment by Rhilip** [comment]
获取？应该是设置吧

**Comment by haig233** [comment]
> 获取？应该是设置吧

对，可能描述不够清楚

**Comment by Rhilip** [comment]
closed: https://github.com/Rhilip/pt-gen-cfworker/commit/76c5dcd19e82993cbe82464f48942645b2b00353 , https://github.com/Rhilip/pt-gen-cfworker/commit/6d3b0547608fcd68da9afcfd761659d05e606f9f

但是我不确定对于此Cookies的有效期信息，demo站点可能不会设置该变量
