### ISSUE TITLE
直接复制 `script.js` 文件无法使用

### ISSUE THREAD

**Issue by qq289531426** [Rhilip/pt-gen-cfworker#22]
最近pt-gen用不了了，想自建，貌似可以使用cloudflare.com搭建，只不过缺少小白教程，可否指教一下，目前已经复制build分支下的 script.js文件。到cloudflare脚本窗口下，运行但是搜索不出信息，不知道还有哪部没有做，可否教下呢
![微信截图_20210816112523](https://user-images.githubusercontent.com/67469239/129507583-546fe943-6a27-4fb5-9951-5780d3abae3b.png)

**Comment by Rhilip** [comment]
可能是缺环境变量，去worker的设置页面加一下首页的两个变量（为空值就行）

**Comment by qq289531426** [comment]
谢谢大佬，我已经弄好了，感谢分享的代码

**Comment by Frankcsc** [comment]
> 谢谢大佬，我已经弄好了，感谢分享的代码

遇到了相同的问题，添加了环境变量也不行（禁止为空），请问您是如何解决的

![图片](https://github.com/user-attachments/assets/c720accd-a1e3-4508-bec7-f4efff241803)
