### ISSUE TITLE
增加多cookie

### ISSUE THREAD

**Issue by daomengRen** [Rhilip/pt-gen-cfworker#24]
# 复现步骤

1. 请指出是哪个域名能够复现该问题？

- [ ] https://ptgen.rhilip.info/
- [ ] https://ptgen.rhilip.workers.dev/
- [ ] 其他非官方API Point： （请修改成对应域名）

2. 如果是非官方域名出现的问题，在上面的官方API Point中能否复现？（使用官方域名请跳过）

- [ ] 在 https://ptgen.rhilip.info/ 域名中能复现。
- [ ] 在 https://ptgen.rhilip.workers.dev/ 域名中能复现。
- [ ] 均不能复现。

3. 错误链接？

# 其他信息

发种时频繁使用，豆瓣会弹出检测界面，能否增加多个cookie变量，一个频繁了，更换另一个，当然，不清楚豆瓣是如何检测的，如果和cookie无关的话，那这样也没用了。

**Comment by Rhilip** [comment]
意义不是很大，我更觉得是因为有些人滥用导致cf服务器ip被豆瓣风控。
如果你频繁使用，更建议使用用户脚本实现
- https://greasyfork.org/zh-CN/scripts/329484
- https://greasyfork.org/zh-CN/scripts/38878

**Comment by daomengRen** [comment]
好的，谢谢R酱大佬
