### ISSUE TITLE
Need help api point please

### ISSUE THREAD

**Issue by LuciuzHQ** [Rhilip/pt-gen-cfworker#25]
Hello,

I'm sorry but I don't understand how to build my own api point.
Can you help me or explain me how it works please ?

Thank you.

**Comment by Rhilip** [comment]
It is a cloudflare worker script, you can find documents on it's offical website: https://workers.cloudflare.com/
If you don't have build environment, you can use the pre-build script in our build branch: https://github.com/Rhilip/pt-gen-cfworker/tree/build
