### ISSUE TITLE
无法获取豆瓣电影的简介

### ISSUE THREAD

**Issue by heartnn** [Rhilip/pt-gen-cfworker#34]
# 复现步骤

1. 请指出是哪个域名能够复现该问题？

- [x] https://ptgen.rhilip.info/
- [ ] https://ptgen.rhilip.workers.dev/
- [ ] 其他非官方API Point： （请修改成对应域名）

2. 如果是非官方域名出现的问题，在上面的官方API Point中能否复现？（使用官方域名请跳过）

- [x] 在 https://ptgen.rhilip.info/ 域名中能复现。
- [ ] 在 https://ptgen.rhilip.workers.dev/ 域名中能复现。
- [ ] 均不能复现。

3. 错误链接？

https://movie.douban.com/subject/30211551/

# 其他信息

自建的cf上也无法获取。

```
◎简　　介

　　暂无相关剧情介绍
```

**Comment by Rhilip** [comment]
![image](https://user-images.githubusercontent.com/13842140/204773909-fa65353e-322c-477a-971f-f698c3bc455a.png)
不能复现

**Comment by heartnn** [comment]
我说的是简介部分，别的部分都是正常的，简介那里一直显示为`暂无相关剧情介绍`，您在确认一下。
