### ISSUE TITLE
用imdb搜索不到豆瓣信息

### ISSUE THREAD

**Issue by daomengRen** [Rhilip/pt-gen-cfworker#36]
# 复现步骤

1. 请指出是哪个域名能够复现该问题？

- [ ] https://hudbt.autofeed.workers.dev/

3. 错误链接？

https://hudbt.autofeed.workers.dev/?search=tt0468569&source=douban

# 其他信息

```
{
  "success": false,
  "error": null,
  "format": "",
  "copyright": "Powered by @Rhilip",
  "version": "0.6.4",
  "generate_at": 1682227252101,
  "data": []
}
```
data为空

**Comment by Rhilip** [comment]
豆瓣快捷搜索接口搜索imdb编号时，不返回对应结果。不是PtGen的问题。
测试链接如下：
https://movie.douban.com/j/subject_suggest?q=tt0468569
