### ISSUE TITLE
豆瓣海报链接不可用

### ISSUE THREAD

**Issue by BFDZ** [Rhilip/pt-gen-cfworker#4]
pt-gen-cfworker 生成的豆瓣海报链接被豆瓣设置了防盗链，pt-gen生成的链接是可用的。
```
[img]https://img1.doubanio.com/view/photo/l/public/p2546360443.jpg[/img]
[img]https://img1.doubanio.com/view/photo/l_ratio_poster/public/p2546360443.jpg[/img]
```
[![lwO3WQ.jpg](https://s2.ax1x.com/2020/01/04/lwO3WQ.jpg)](https://imgchr.com/i/lwO3WQ)
[![lwOlFS.jpg](https://s2.ax1x.com/2020/01/04/lwOlFS.jpg)](https://imgchr.com/i/lwOlFS)

**Comment by Rhilip** [comment]
看起来更像是 我写错正则相关替换方法了

https://github.com/Rhilip/pt-gen-cfworker/blob/41c3d5a961fa52f74320626b8e28f5c250b79991/index.js#L364-L365
