### ISSUE TITLE
游戏一些连接的试了不成功

### ISSUE THREAD

**Issue by ted423** [Rhilip/pt-gen-cfworker#5]
https://www.epicgames.com/store/zh-Hant/product/control/home
这个没反应
然后
https://indienova.com/game/valkyria-chronicles-2
生成的头图是不让看的
生成的是jpg，但网页显示用的是https://hive.indienova.com/ranch/gamedb/2018/08/cover/15341387804kxi.jpg_webp

**Comment by Rhilip** [comment]
epic那边他们修改apipoint了，所以导致没法响应。
indienova我试了下生成的img链接是 <https://hive.indienova.com/ranch/gamedb/2018/08/cover/15341387804kxi.jpg> 这个链接也是可以直接打开的，但是应该是他们服务器那边有限制，所以没法再别的网站上使用。
你提供的`.jpg_webp`其实也没法在别的网站上使用，也是404响应。
这块我更建议将其下载下来（直接打开是可以的），然后再做上传。

**Comment by ted423** [comment]
> epic那边他们修改apipoint了，所以导致没法响应。
> indienova我试了下生成的img链接是 https://hive.indienova.com/ranch/gamedb/2018/08/cover/15341387804kxi.jpg 这个链接也是可以直接打开的，但是应该是他们服务器那边有限制，所以没法再别的网站上使用。
> 你提供的`.jpg_webp`其实也没法在别的网站上使用，也是404响应。
> 这块我更建议将其下载下来（直接打开是可以的），然后再做上传。


![image](https://user-images.githubusercontent.com/7042766/79568323-3947db80-80e8-11ea-8ecc-897b3495ea41.png)

这是我改了下猫站上的 PSPGAME Valkyria Chronicles II PACK
这是发这个issue时改的，应该不是缓存

**Comment by Rhilip** [comment]
可能是因为这个站设置了 `<meta name="referrer" />` 或者在img部分单独使用noreferrer。
对请求进行检查可以发现，无论是 `.jpg` 还是 `.jpg_webp` 都会因为referrer头不对被拦截，
![image](https://user-images.githubusercontent.com/13842140/79570644-672f1f00-80ec-11ea-8330-8444070d91d7.png)

**Comment by Rhilip** [comment]
鉴于indienova的头图不显示（无论是 `.jpg_webp` 还是 `.jpg`结尾），是因为indienova处的Referer ACL，非Pt-Gen处可以控制。
epicgames的相关问题已经解决，此issue关闭
