### ISSUE TITLE
 漫画获取信息出错

### ISSUE THREAD

**Issue by ted423** [Rhilip/pt-gen-cfworker#6]
https://bgm.tv/subject/109281
![image](https://user-images.githubusercontent.com/7042766/85580619-78f1ed00-b66e-11ea-8c62-3edb615945e3.png)
![image](https://user-images.githubusercontent.com/7042766/85580740-945cf800-b66e-11ea-946a-c2a6a0647141.png)

**Comment by ted423** [comment]
才发现应该用https://bgm.tv/subject/82314

**Comment by Rhilip** [comment]
在最初编写的时候就没考虑过漫画类型。所以你会看到有这种设计。

https://github.com/Rhilip/pt-gen-cfworker/blob/369c84344cae277d2a83d224b0684ee251300b28/index.js#L696-L697

如果你有啥比较好的漫画类型信息网站，我可以考虑做一下整理。

**Comment by ted423** [comment]
> 在最初编写的时候就没考虑过漫画类型。所以你会看到有这种设计。
> 
> https://github.com/Rhilip/pt-gen-cfworker/blob/369c84344cae277d2a83d224b0684ee251300b28/index.js#L696-L697
> 
> 如果你有啥比较好的漫画类型信息网站，我可以考虑做一下整理。

有也只有国外的了
https://myanimelist.net/manga/39627/Tora_Kiss__A_School_Odyssey
还有就是同人的
https://www.doujinshi.org/book/872808/
